TARGETS	= $(OBJDIR)basename $(OBJDIR)cat $(OBJDIR)chgrp $(OBJDIR)chmod $(OBJDIR)chown $(OBJDIR)cksum $(OBJDIR)cmp $(OBJDIR)cp $(OBJDIR)date $(OBJDIR)df $(OBJDIR)dirname $(OBJDIR)du $(OBJDIR)echo $(OBJDIR)false $(OBJDIR)file $(OBJDIR)find $(OBJDIR)head $(OBJDIR)id $(OBJDIR)kill $(OBJDIR)link $(OBJDIR)ln $(OBJDIR)locale $(OBJDIR)logname $(OBJDIR)ls $(OBJDIR)mkdir $(OBJDIR)mkfifo $(OBJDIR)more $(OBJDIR)mv $(OBJDIR)nice $(OBJDIR)pr $(OBJDIR)printf $(OBJDIR)ps $(OBJDIR)pwd $(OBJDIR)renice $(OBJDIR)rm $(OBJDIR)rmdir $(OBJDIR)sleep $(OBJDIR)strings $(OBJDIR)tail $(OBJDIR)test $(OBJDIR)time $(OBJDIR)touch $(OBJDIR)true $(OBJDIR)tty $(OBJDIR)uname $(OBJDIR)uniq $(OBJDIR)unlink $(OBJDIR)wc $(OBJDIR)who
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
BINDIR	= $(PREFIX)/bin
SBINDIR	= $(PREFIX)/sbin
CC	= cc
CPPFLAGSF=
CPPFLAGS=
CFLAGSF	= -W
CFLAGS	= -Wall -g -O2 -pedantic
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

basename_OBJS = $(OBJDIR)basename.o
basename_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
basename_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)basename: $(basename_OBJS)
	$(CC) -o $(OBJDIR)basename $(basename_OBJS) $(basename_LDFLAGS)

cat_OBJS = $(OBJDIR)cat.o
cat_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cat_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)cat: $(cat_OBJS)
	$(CC) -o $(OBJDIR)cat $(cat_OBJS) $(cat_LDFLAGS)

chgrp_OBJS = $(OBJDIR)chgrp.o
chgrp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chgrp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)chgrp: $(chgrp_OBJS)
	$(CC) -o $(OBJDIR)chgrp $(chgrp_OBJS) $(chgrp_LDFLAGS)

chmod_OBJS = $(OBJDIR)chmod.o
chmod_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chmod_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)chmod: $(chmod_OBJS)
	$(CC) -o $(OBJDIR)chmod $(chmod_OBJS) $(chmod_LDFLAGS)

chown_OBJS = $(OBJDIR)chown.o
chown_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chown_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)chown: $(chown_OBJS)
	$(CC) -o $(OBJDIR)chown $(chown_OBJS) $(chown_LDFLAGS)

cksum_OBJS = $(OBJDIR)cksum.o
cksum_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cksum_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)cksum: $(cksum_OBJS)
	$(CC) -o $(OBJDIR)cksum $(cksum_OBJS) $(cksum_LDFLAGS)

cmp_OBJS = $(OBJDIR)cmp.o
cmp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cmp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)cmp: $(cmp_OBJS)
	$(CC) -o $(OBJDIR)cmp $(cmp_OBJS) $(cmp_LDFLAGS)

cp_OBJS = $(OBJDIR)cp.o
cp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)cp: $(cp_OBJS)
	$(CC) -o $(OBJDIR)cp $(cp_OBJS) $(cp_LDFLAGS)

date_OBJS = $(OBJDIR)date.o
date_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
date_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)date: $(date_OBJS)
	$(CC) -o $(OBJDIR)date $(date_OBJS) $(date_LDFLAGS)

df_OBJS = $(OBJDIR)df.o
df_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
df_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)df: $(df_OBJS)
	$(CC) -o $(OBJDIR)df $(df_OBJS) $(df_LDFLAGS)

dirname_OBJS = $(OBJDIR)dirname.o
dirname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
dirname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)dirname: $(dirname_OBJS)
	$(CC) -o $(OBJDIR)dirname $(dirname_OBJS) $(dirname_LDFLAGS)

du_OBJS = $(OBJDIR)du.o
du_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
du_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)du: $(du_OBJS)
	$(CC) -o $(OBJDIR)du $(du_OBJS) $(du_LDFLAGS)

echo_OBJS = $(OBJDIR)echo.o
echo_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
echo_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)echo: $(echo_OBJS)
	$(CC) -o $(OBJDIR)echo $(echo_OBJS) $(echo_LDFLAGS)

false_OBJS = $(OBJDIR)false.o
false_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
false_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)false: $(false_OBJS)
	$(CC) -o $(OBJDIR)false $(false_OBJS) $(false_LDFLAGS)

file_OBJS = $(OBJDIR)file.o
file_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
file_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)file: $(file_OBJS)
	$(CC) -o $(OBJDIR)file $(file_OBJS) $(file_LDFLAGS)

find_OBJS = $(OBJDIR)find.o
find_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
find_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)find: $(find_OBJS)
	$(CC) -o $(OBJDIR)find $(find_OBJS) $(find_LDFLAGS)

head_OBJS = $(OBJDIR)head.o
head_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
head_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)head: $(head_OBJS)
	$(CC) -o $(OBJDIR)head $(head_OBJS) $(head_LDFLAGS)

id_OBJS = $(OBJDIR)id.o
id_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
id_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)id: $(id_OBJS)
	$(CC) -o $(OBJDIR)id $(id_OBJS) $(id_LDFLAGS)

kill_OBJS = $(OBJDIR)kill.o
kill_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
kill_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)kill: $(kill_OBJS)
	$(CC) -o $(OBJDIR)kill $(kill_OBJS) $(kill_LDFLAGS)

link_OBJS = $(OBJDIR)link.o
link_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
link_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)link: $(link_OBJS)
	$(CC) -o $(OBJDIR)link $(link_OBJS) $(link_LDFLAGS)

ln_OBJS = $(OBJDIR)ln.o
ln_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ln_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)ln: $(ln_OBJS)
	$(CC) -o $(OBJDIR)ln $(ln_OBJS) $(ln_LDFLAGS)

locale_OBJS = $(OBJDIR)locale.o
locale_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
locale_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)locale: $(locale_OBJS)
	$(CC) -o $(OBJDIR)locale $(locale_OBJS) $(locale_LDFLAGS)

logname_OBJS = $(OBJDIR)logname.o
logname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
logname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)logname: $(logname_OBJS)
	$(CC) -o $(OBJDIR)logname $(logname_OBJS) $(logname_LDFLAGS)

ls_OBJS = $(OBJDIR)ls.o
ls_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ls_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)ls: $(ls_OBJS)
	$(CC) -o $(OBJDIR)ls $(ls_OBJS) $(ls_LDFLAGS)

mkdir_OBJS = $(OBJDIR)mkdir.o
mkdir_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mkdir_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)mkdir: $(mkdir_OBJS)
	$(CC) -o $(OBJDIR)mkdir $(mkdir_OBJS) $(mkdir_LDFLAGS)

mkfifo_OBJS = $(OBJDIR)mkfifo.o
mkfifo_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mkfifo_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)mkfifo: $(mkfifo_OBJS)
	$(CC) -o $(OBJDIR)mkfifo $(mkfifo_OBJS) $(mkfifo_LDFLAGS)

more_OBJS = $(OBJDIR)more.o
more_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
more_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)more: $(more_OBJS)
	$(CC) -o $(OBJDIR)more $(more_OBJS) $(more_LDFLAGS)

mv_OBJS = $(OBJDIR)mv.o
mv_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mv_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)mv: $(mv_OBJS)
	$(CC) -o $(OBJDIR)mv $(mv_OBJS) $(mv_LDFLAGS)

nice_OBJS = $(OBJDIR)nice.o
nice_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
nice_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)nice: $(nice_OBJS)
	$(CC) -o $(OBJDIR)nice $(nice_OBJS) $(nice_LDFLAGS)

pr_OBJS = $(OBJDIR)pr.o
pr_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
pr_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)pr: $(pr_OBJS)
	$(CC) -o $(OBJDIR)pr $(pr_OBJS) $(pr_LDFLAGS)

printf_OBJS = $(OBJDIR)printf.o
printf_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
printf_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)printf: $(printf_OBJS)
	$(CC) -o $(OBJDIR)printf $(printf_OBJS) $(printf_LDFLAGS)

ps_OBJS = $(OBJDIR)ps.o
ps_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ps_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)ps: $(ps_OBJS)
	$(CC) -o $(OBJDIR)ps $(ps_OBJS) $(ps_LDFLAGS)

pwd_OBJS = $(OBJDIR)pwd.o
pwd_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
pwd_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)pwd: $(pwd_OBJS)
	$(CC) -o $(OBJDIR)pwd $(pwd_OBJS) $(pwd_LDFLAGS)

renice_OBJS = $(OBJDIR)renice.o
renice_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
renice_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)renice: $(renice_OBJS)
	$(CC) -o $(OBJDIR)renice $(renice_OBJS) $(renice_LDFLAGS)

rm_OBJS = $(OBJDIR)rm.o
rm_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
rm_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)rm: $(rm_OBJS)
	$(CC) -o $(OBJDIR)rm $(rm_OBJS) $(rm_LDFLAGS)

rmdir_OBJS = $(OBJDIR)rmdir.o
rmdir_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
rmdir_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)rmdir: $(rmdir_OBJS)
	$(CC) -o $(OBJDIR)rmdir $(rmdir_OBJS) $(rmdir_LDFLAGS)

sleep_OBJS = $(OBJDIR)sleep.o
sleep_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
sleep_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)sleep: $(sleep_OBJS)
	$(CC) -o $(OBJDIR)sleep $(sleep_OBJS) $(sleep_LDFLAGS)

strings_OBJS = $(OBJDIR)strings.o
strings_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
strings_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)strings: $(strings_OBJS)
	$(CC) -o $(OBJDIR)strings $(strings_OBJS) $(strings_LDFLAGS)

tail_OBJS = $(OBJDIR)tail.o
tail_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
tail_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)tail: $(tail_OBJS)
	$(CC) -o $(OBJDIR)tail $(tail_OBJS) $(tail_LDFLAGS)

test_OBJS = $(OBJDIR)test.o
test_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
test_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)test: $(test_OBJS)
	$(CC) -o $(OBJDIR)test $(test_OBJS) $(test_LDFLAGS)

time_OBJS = $(OBJDIR)time.o
time_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
time_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)time: $(time_OBJS)
	$(CC) -o $(OBJDIR)time $(time_OBJS) $(time_LDFLAGS)

touch_OBJS = $(OBJDIR)touch.o
touch_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
touch_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)touch: $(touch_OBJS)
	$(CC) -o $(OBJDIR)touch $(touch_OBJS) $(touch_LDFLAGS)

true_OBJS = $(OBJDIR)true.o
true_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
true_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)true: $(true_OBJS)
	$(CC) -o $(OBJDIR)true $(true_OBJS) $(true_LDFLAGS)

tty_OBJS = $(OBJDIR)tty.o
tty_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
tty_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)tty: $(tty_OBJS)
	$(CC) -o $(OBJDIR)tty $(tty_OBJS) $(tty_LDFLAGS)

uname_OBJS = $(OBJDIR)uname.o
uname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
uname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)uname: $(uname_OBJS)
	$(CC) -o $(OBJDIR)uname $(uname_OBJS) $(uname_LDFLAGS)

uniq_OBJS = $(OBJDIR)uniq.o
uniq_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
uniq_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)uniq: $(uniq_OBJS)
	$(CC) -o $(OBJDIR)uniq $(uniq_OBJS) $(uniq_LDFLAGS)

unlink_OBJS = $(OBJDIR)unlink.o
unlink_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
unlink_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)unlink: $(unlink_OBJS)
	$(CC) -o $(OBJDIR)unlink $(unlink_OBJS) $(unlink_LDFLAGS)

wc_OBJS = $(OBJDIR)wc.o
wc_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
wc_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)wc: $(wc_OBJS)
	$(CC) -o $(OBJDIR)wc $(wc_OBJS) $(wc_LDFLAGS)

who_OBJS = $(OBJDIR)who.o
who_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
who_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)who: $(who_OBJS)
	$(CC) -o $(OBJDIR)who $(who_OBJS) $(who_LDFLAGS)

$(OBJDIR)basename.o: basename.c
	$(CC) $(basename_CFLAGS) -o $(OBJDIR)basename.o -c basename.c

$(OBJDIR)cat.o: cat.c
	$(CC) $(cat_CFLAGS) -o $(OBJDIR)cat.o -c cat.c

$(OBJDIR)chgrp.o: chgrp.c
	$(CC) $(chgrp_CFLAGS) -o $(OBJDIR)chgrp.o -c chgrp.c

$(OBJDIR)chmod.o: chmod.c common.c
	$(CC) $(chmod_CFLAGS) -o $(OBJDIR)chmod.o -c chmod.c

$(OBJDIR)chown.o: chown.c
	$(CC) $(chown_CFLAGS) -o $(OBJDIR)chown.o -c chown.c

$(OBJDIR)cksum.o: cksum.c
	$(CC) $(cksum_CFLAGS) -o $(OBJDIR)cksum.o -c cksum.c

$(OBJDIR)cmp.o: cmp.c
	$(CC) $(cmp_CFLAGS) -o $(OBJDIR)cmp.o -c cmp.c

$(OBJDIR)cp.o: cp.c
	$(CC) $(cp_CFLAGS) -o $(OBJDIR)cp.o -c cp.c

$(OBJDIR)date.o: date.c
	$(CC) $(date_CFLAGS) -o $(OBJDIR)date.o -c date.c

$(OBJDIR)df.o: df.c
	$(CC) $(df_CFLAGS) -o $(OBJDIR)df.o -c df.c

$(OBJDIR)dirname.o: dirname.c
	$(CC) $(dirname_CFLAGS) -o $(OBJDIR)dirname.o -c dirname.c

$(OBJDIR)du.o: du.c
	$(CC) $(du_CFLAGS) -o $(OBJDIR)du.o -c du.c

$(OBJDIR)echo.o: echo.c
	$(CC) $(echo_CFLAGS) -o $(OBJDIR)echo.o -c echo.c

$(OBJDIR)false.o: false.c
	$(CC) $(false_CFLAGS) -o $(OBJDIR)false.o -c false.c

$(OBJDIR)file.o: file.c
	$(CC) $(file_CFLAGS) -o $(OBJDIR)file.o -c file.c

$(OBJDIR)find.o: find.c
	$(CC) $(find_CFLAGS) -o $(OBJDIR)find.o -c find.c

$(OBJDIR)head.o: head.c
	$(CC) $(head_CFLAGS) -o $(OBJDIR)head.o -c head.c

$(OBJDIR)id.o: id.c
	$(CC) $(id_CFLAGS) -o $(OBJDIR)id.o -c id.c

$(OBJDIR)kill.o: kill.c
	$(CC) $(kill_CFLAGS) -o $(OBJDIR)kill.o -c kill.c

$(OBJDIR)link.o: link.c
	$(CC) $(link_CFLAGS) -o $(OBJDIR)link.o -c link.c

$(OBJDIR)ln.o: ln.c
	$(CC) $(ln_CFLAGS) -o $(OBJDIR)ln.o -c ln.c

$(OBJDIR)locale.o: locale.c
	$(CC) $(locale_CFLAGS) -o $(OBJDIR)locale.o -c locale.c

$(OBJDIR)logname.o: logname.c
	$(CC) $(logname_CFLAGS) -o $(OBJDIR)logname.o -c logname.c

$(OBJDIR)ls.o: ls.c
	$(CC) $(ls_CFLAGS) -o $(OBJDIR)ls.o -c ls.c

$(OBJDIR)mkdir.o: mkdir.c common.c
	$(CC) $(mkdir_CFLAGS) -o $(OBJDIR)mkdir.o -c mkdir.c

$(OBJDIR)mkfifo.o: mkfifo.c common.c
	$(CC) $(mkfifo_CFLAGS) -o $(OBJDIR)mkfifo.o -c mkfifo.c

$(OBJDIR)more.o: more.c
	$(CC) $(more_CFLAGS) -o $(OBJDIR)more.o -c more.c

$(OBJDIR)mv.o: mv.c
	$(CC) $(mv_CFLAGS) -o $(OBJDIR)mv.o -c mv.c

$(OBJDIR)nice.o: nice.c
	$(CC) $(nice_CFLAGS) -o $(OBJDIR)nice.o -c nice.c

$(OBJDIR)pr.o: pr.c
	$(CC) $(pr_CFLAGS) -o $(OBJDIR)pr.o -c pr.c

$(OBJDIR)printf.o: printf.c
	$(CC) $(printf_CFLAGS) -o $(OBJDIR)printf.o -c printf.c

$(OBJDIR)ps.o: ps.c
	$(CC) $(ps_CFLAGS) -o $(OBJDIR)ps.o -c ps.c

$(OBJDIR)pwd.o: pwd.c
	$(CC) $(pwd_CFLAGS) -o $(OBJDIR)pwd.o -c pwd.c

$(OBJDIR)renice.o: renice.c
	$(CC) $(renice_CFLAGS) -o $(OBJDIR)renice.o -c renice.c

$(OBJDIR)rm.o: rm.c
	$(CC) $(rm_CFLAGS) -o $(OBJDIR)rm.o -c rm.c

$(OBJDIR)rmdir.o: rmdir.c
	$(CC) $(rmdir_CFLAGS) -o $(OBJDIR)rmdir.o -c rmdir.c

$(OBJDIR)sleep.o: sleep.c
	$(CC) $(sleep_CFLAGS) -o $(OBJDIR)sleep.o -c sleep.c

$(OBJDIR)strings.o: strings.c
	$(CC) $(strings_CFLAGS) -o $(OBJDIR)strings.o -c strings.c

$(OBJDIR)tail.o: tail.c
	$(CC) $(tail_CFLAGS) -o $(OBJDIR)tail.o -c tail.c

$(OBJDIR)test.o: test.c
	$(CC) $(test_CFLAGS) -o $(OBJDIR)test.o -c test.c

$(OBJDIR)time.o: time.c
	$(CC) $(time_CFLAGS) -o $(OBJDIR)time.o -c time.c

$(OBJDIR)touch.o: touch.c
	$(CC) $(touch_CFLAGS) -o $(OBJDIR)touch.o -c touch.c

$(OBJDIR)true.o: true.c
	$(CC) $(true_CFLAGS) -o $(OBJDIR)true.o -c true.c

$(OBJDIR)tty.o: tty.c
	$(CC) $(tty_CFLAGS) -o $(OBJDIR)tty.o -c tty.c

$(OBJDIR)uname.o: uname.c
	$(CC) $(uname_CFLAGS) -o $(OBJDIR)uname.o -c uname.c

$(OBJDIR)uniq.o: uniq.c
	$(CC) $(uniq_CFLAGS) -o $(OBJDIR)uniq.o -c uniq.c

$(OBJDIR)unlink.o: unlink.c
	$(CC) $(unlink_CFLAGS) -o $(OBJDIR)unlink.o -c unlink.c

$(OBJDIR)wc.o: wc.c
	$(CC) $(wc_CFLAGS) -o $(OBJDIR)wc.o -c wc.c

$(OBJDIR)who.o: who.c
	$(CC) $(who_CFLAGS) -o $(OBJDIR)who.o -c who.c

clean:
	$(RM) -- $(basename_OBJS) $(cat_OBJS) $(chgrp_OBJS) $(chmod_OBJS) $(chown_OBJS) $(cksum_OBJS) $(cmp_OBJS) $(cp_OBJS) $(date_OBJS) $(df_OBJS) $(dirname_OBJS) $(du_OBJS) $(echo_OBJS) $(false_OBJS) $(file_OBJS) $(find_OBJS) $(head_OBJS) $(id_OBJS) $(kill_OBJS) $(link_OBJS) $(ln_OBJS) $(locale_OBJS) $(logname_OBJS) $(ls_OBJS) $(mkdir_OBJS) $(mkfifo_OBJS) $(more_OBJS) $(mv_OBJS) $(nice_OBJS) $(pr_OBJS) $(printf_OBJS) $(ps_OBJS) $(pwd_OBJS) $(renice_OBJS) $(rm_OBJS) $(rmdir_OBJS) $(sleep_OBJS) $(strings_OBJS) $(tail_OBJS) $(test_OBJS) $(time_OBJS) $(touch_OBJS) $(true_OBJS) $(tty_OBJS) $(uname_OBJS) $(uniq_OBJS) $(unlink_OBJS) $(wc_OBJS) $(who_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)basename $(DESTDIR)$(BINDIR)/basename
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)cat $(DESTDIR)$(BINDIR)/cat
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)chgrp $(DESTDIR)$(BINDIR)/chgrp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)chmod $(DESTDIR)$(BINDIR)/chmod
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)chown $(DESTDIR)$(BINDIR)/chown
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)cksum $(DESTDIR)$(BINDIR)/cksum
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)cmp $(DESTDIR)$(BINDIR)/cmp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)cp $(DESTDIR)$(BINDIR)/cp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)date $(DESTDIR)$(BINDIR)/date
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)df $(DESTDIR)$(BINDIR)/df
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)dirname $(DESTDIR)$(BINDIR)/dirname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)du $(DESTDIR)$(BINDIR)/du
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)echo $(DESTDIR)$(BINDIR)/echo
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)false $(DESTDIR)$(BINDIR)/false
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)file $(DESTDIR)$(BINDIR)/file
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)find $(DESTDIR)$(BINDIR)/find
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)head $(DESTDIR)$(BINDIR)/head
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)id $(DESTDIR)$(BINDIR)/id
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)kill $(DESTDIR)$(BINDIR)/kill
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)link $(DESTDIR)$(BINDIR)/link
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)ln $(DESTDIR)$(BINDIR)/ln
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)locale $(DESTDIR)$(BINDIR)/locale
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)logname $(DESTDIR)$(BINDIR)/logname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)ls $(DESTDIR)$(BINDIR)/ls
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)mkdir $(DESTDIR)$(BINDIR)/mkdir
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)mkfifo $(DESTDIR)$(BINDIR)/mkfifo
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)more $(DESTDIR)$(BINDIR)/more
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)mv $(DESTDIR)$(BINDIR)/mv
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)nice $(DESTDIR)$(BINDIR)/nice
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)pr $(DESTDIR)$(BINDIR)/pr
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)printf $(DESTDIR)$(BINDIR)/printf
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)ps $(DESTDIR)$(BINDIR)/ps
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)pwd $(DESTDIR)$(BINDIR)/pwd
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)renice $(DESTDIR)$(BINDIR)/renice
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)rm $(DESTDIR)$(BINDIR)/rm
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)rmdir $(DESTDIR)$(BINDIR)/rmdir
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)sleep $(DESTDIR)$(BINDIR)/sleep
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)strings $(DESTDIR)$(BINDIR)/strings
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)tail $(DESTDIR)$(BINDIR)/tail
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)test $(DESTDIR)$(BINDIR)/test
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)time $(DESTDIR)$(BINDIR)/time
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)touch $(DESTDIR)$(BINDIR)/touch
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)true $(DESTDIR)$(BINDIR)/true
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)tty $(DESTDIR)$(BINDIR)/tty
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)uname $(DESTDIR)$(BINDIR)/uname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)uniq $(DESTDIR)$(BINDIR)/uniq
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)unlink $(DESTDIR)$(BINDIR)/unlink
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)wc $(DESTDIR)$(BINDIR)/wc
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)who $(DESTDIR)$(BINDIR)/who

uninstall:
	$(RM) -- $(DESTDIR)$(BINDIR)/basename
	$(RM) -- $(DESTDIR)$(BINDIR)/cat
	$(RM) -- $(DESTDIR)$(BINDIR)/chgrp
	$(RM) -- $(DESTDIR)$(BINDIR)/chmod
	$(RM) -- $(DESTDIR)$(BINDIR)/chown
	$(RM) -- $(DESTDIR)$(BINDIR)/cksum
	$(RM) -- $(DESTDIR)$(BINDIR)/cmp
	$(RM) -- $(DESTDIR)$(BINDIR)/cp
	$(RM) -- $(DESTDIR)$(BINDIR)/date
	$(RM) -- $(DESTDIR)$(BINDIR)/df
	$(RM) -- $(DESTDIR)$(BINDIR)/dirname
	$(RM) -- $(DESTDIR)$(BINDIR)/du
	$(RM) -- $(DESTDIR)$(BINDIR)/echo
	$(RM) -- $(DESTDIR)$(BINDIR)/false
	$(RM) -- $(DESTDIR)$(BINDIR)/file
	$(RM) -- $(DESTDIR)$(BINDIR)/find
	$(RM) -- $(DESTDIR)$(BINDIR)/head
	$(RM) -- $(DESTDIR)$(BINDIR)/id
	$(RM) -- $(DESTDIR)$(BINDIR)/kill
	$(RM) -- $(DESTDIR)$(BINDIR)/link
	$(RM) -- $(DESTDIR)$(BINDIR)/ln
	$(RM) -- $(DESTDIR)$(BINDIR)/locale
	$(RM) -- $(DESTDIR)$(BINDIR)/logname
	$(RM) -- $(DESTDIR)$(BINDIR)/ls
	$(RM) -- $(DESTDIR)$(BINDIR)/mkdir
	$(RM) -- $(DESTDIR)$(BINDIR)/mkfifo
	$(RM) -- $(DESTDIR)$(BINDIR)/more
	$(RM) -- $(DESTDIR)$(BINDIR)/mv
	$(RM) -- $(DESTDIR)$(BINDIR)/nice
	$(RM) -- $(DESTDIR)$(BINDIR)/pr
	$(RM) -- $(DESTDIR)$(BINDIR)/printf
	$(RM) -- $(DESTDIR)$(BINDIR)/ps
	$(RM) -- $(DESTDIR)$(BINDIR)/pwd
	$(RM) -- $(DESTDIR)$(BINDIR)/renice
	$(RM) -- $(DESTDIR)$(BINDIR)/rm
	$(RM) -- $(DESTDIR)$(BINDIR)/rmdir
	$(RM) -- $(DESTDIR)$(BINDIR)/sleep
	$(RM) -- $(DESTDIR)$(BINDIR)/strings
	$(RM) -- $(DESTDIR)$(BINDIR)/tail
	$(RM) -- $(DESTDIR)$(BINDIR)/test
	$(RM) -- $(DESTDIR)$(BINDIR)/time
	$(RM) -- $(DESTDIR)$(BINDIR)/touch
	$(RM) -- $(DESTDIR)$(BINDIR)/true
	$(RM) -- $(DESTDIR)$(BINDIR)/tty
	$(RM) -- $(DESTDIR)$(BINDIR)/uname
	$(RM) -- $(DESTDIR)$(BINDIR)/uniq
	$(RM) -- $(DESTDIR)$(BINDIR)/unlink
	$(RM) -- $(DESTDIR)$(BINDIR)/wc
	$(RM) -- $(DESTDIR)$(BINDIR)/who

.PHONY: all clean distclean install uninstall
